// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScreenBin.Data;

namespace ScreenBin.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211227024210_Screenshots_ScreenshotTable")]
    partial class Screenshots_ScreenshotTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ScreenBin.Areas.Screenshots.Models.Screenshot", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(191)")
                        .HasMaxLength(191);

                    b.Property<string>("RelativePath")
                        .HasColumnType("varchar(300)")
                        .HasMaxLength(300);

                    b.Property<string>("Title")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255);

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Screenshots");
                });
#pragma warning restore 612, 618
        }
    }
}
